
name: Bug report
about: Create a report to help us improve
title: '[bug]: '
labels: ['bug']
body:
 - type: markdown
    attributes:
      value: |
        Thank you for coming here to submit a bug report. We care about anything from big to small relating to MHSF, making a better experience for you and others.

        Try and be as descriptive as possible & type in a way thats able to understood by other contributors.
